=== WHITE-HAT-JESTER/CST1340-BOOK-SHOP/books.dtd
<!DOCTYPE bookshop>

<!--Root elemnt containing all the books being listed-->
<!ELEMENT bookshop(book+)>

<!--the elment book will contain the data but ISBN can be left empty-->
<!ELEMENT book(bookcover,title,description,author,ISBN?, price, year)>
<!--Each book must have the category attribute (horror, sci-fi, non-fiction, romance, children, mystery, thriller)-->
<!ATTLIST book category CDATA #REQUIRED>

<!--bookcover stores the image url-->
<!ELEMENT bookcover EMPTY>
<!ATTLIST bookcover url CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT author (firstname, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>

<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== WHITE-HAT-JESTER/CST1340-BOOK-SHOP/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookshop SYSTEM "books.dtd">
<?xml-stylesheet type="text/xsl" text="DEAR GUILTY READER" href="XSL.xsl"?>

<bookshop>
	<book category="sci-fi">
		<bookcover url="https://stateofmind13.com/wp-content/uploads/2012/02/the-hunger-games-book-cover.jpg"/>
		<title  >The Hunger Games</title>
		<description>In a dystopian future, Katniss Everdeen volunteers for a deadly bunger games to save her siser in turn creating a rebellion againt the opposing goverment</description>
		<author>
			<firstname>Suzanne</firstname> 
			<lastname>Collins</lastname>
		</author>
		<ISBN>9780439023481 </ISBN>
		<price>16.50</price>
		<year>2008</year>
	</book>

	<book category="sci-fi">
		<bookcover url="https://static.wixstatic.com/media/e61731_e1fc5aa9aa3a405c94536f6692b412be~mv2.jpg/v1/fill/w_188,h_284,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/e61731_e1fc5aa9aa3a405c94536f6692b412be~mv2.jpg"/>
		<title>Dune</title>
		<description>On a desert planet, Paul Atreides navigates through politics, ecology and mysticism to become a rebellion leader.</description>
		<author>
			<firstname>Frank</firstname>
			<lastname>Herbert</lastname>
		</author> 
		<ISBN>9780441172719</ISBN>
		<price>25.20</price>
		<year>1965</year>
	</book> 

	<book category="sci-fi">
		<bookcover url="https://cdn.dc5.ro/img-prod/2007693969-1.jpeg"/>
		<title>Neuromancer</title>
		<description>Geralt River, a monster hunter,navigating through a medevil fantasy world filled with politics and danger.</description>
		<author>
			<firstname>William</firstname>
			<lastname>Gibson</lastname>
		</author> 
		<ISBN>9780441569595</ISBN>
		<price>21.00</price>
		<year>1984</year>
	</book> 

	<book category="children">
		<bookcover url="https://c7.alamy.com/comp/2DBK1FJ/the-gruffalo-by-julia-donaldson-and-axel-scheffler-childrens-picture-book-2DBK1FJ.jpg"/>
		<title>The Gruffalo</title>
		<description>The gruffalo is a fearsome creature creaed by a mouse to save itself from creature in the woods but encounters a suprise.</description>
		<author>
			<firstname>Julia</firstname> 
			<lastname>Donaldson</lastname>
		</author>
		<ISBN>9780142403877 </ISBN>
		<price>10.20</price>
		<year>2000</year>
	</book>

	<book category="children">
		<bookcover url="https://www.fictiondb.com/coversth/th_0689829531.jpg"/>
		<title>Olivia</title>
		<description>A herioc and mischiveous piglet named Olivia who does things her own way.</description>
		<author>
			<firstname>Ian</firstname> 
			<lastname>Falconer</lastname>
		</author>
		<ISBN>9780688168583</ISBN>
		<price>12.00</price>
		<year>2000</year>
	</book>
    
	<book category="thriller">
		<bookcover url="https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/08125029341869.55eebb25e5ed5.jpg"/>
		<title>Gone Girl</title>
		<description>A twisted thriller of a marriage that turns out to be a deadly game of cat and mouse.</description>
		<author>
			<firstname>Gillian</firstname> 
			<lastname>Flynn</lastname>
		</author>
		<ISBN>9780307588364</ISBN>
		<price>12.10</price>
		<year>2012</year>
	</book>

	<book category="thriller">
		<bookcover url="https://m.media-amazon.com/images/I/41rIlFGkRDL._SY445_SX342_FMwebp_.jpg"/>
		<title>My Husbands Wife</title>
		<description>Psychological thriller about a women waking up from a cooma to find her husband's new marriage to her sister is a shocking twist to her quest of truth and identity.</description>
		<author>
			<firstname>Alice</firstname> 
			<lastname>Feeney</lastname>
		</author>
		<ISBN>9781538753952</ISBN>
		<price>14.10</price>
		<year>2026</year>
	</book>
    
	<book category="mystery"> 
		<bookcover url="https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781982150341/devil-in-a-blue-dress-30th-anniversary-edition-9781982150341_lg.jpg"/>
		<title>Devil in a Blue Dress</title>
		<description>Easy Rawlins, a black World War Two vet searches for a missing white woman in 1948LA, navigating racism and corruption</description>
		<author>
			<firstname>Walter</firstname> 
			<lastname>Mosley</lastname>
		</author>
		<ISBN>9781982150341</ISBN>
		<price>16.20</price>
		<year>1990</year>
	</book>

   <book category="mystery">
		<bookcover url="https://m.media-amazon.com/images/I/514E477GU1L.jpg"/>
		<title>And Then There Were None</title>
		<description>Ten strangers are invited to an isolated island, only to be killed off one by one.</description>
		<author>
			<firstname>Agatha</firstname> 
			<lastname>Christie</lastname>
		</author>
		<ISBN>9781443435134</ISBN>
		<price>20.00</price>
		<year>1939</year>
	</book>

	<book category="horror">
		<bookcover url="https://m.media-amazon.com/images/I/41igFYPUV9L._SY445_SX342_QL70_FMwebp_.jpg"/>
		<title>The Haunting Hill House</title>
		<description>A group explores a mansion with a history of supernatural events. </description>
		<author>
			<firstname>Shirley</firstname> 
			<lastname>Jackson</lastname>
		</author>
		<ISBN>9780451524938</ISBN>
		<price>15.20</price>
		<year>1959</year>
	</book>

   <book category="horror">
		<bookcover url="https://m.media-amazon.com/images/I/513x+J9aAHL._SY300_SX300_QL70_FMwebp_.jpg"/>
		<title>The Shining</title>
		<description>A family gets trapped in a haunted hotel with terrifying consequences.</description>
		<author>
			<firstname>Stephen</firstname> 
			<lastname>King</lastname>
		</author>
		<ISBN>9780307743653</ISBN>
		<price>16.20</price>
		<year>1977</year>
	</book>

	<book category="fantasy">
		<bookcover url="https://m.media-amazon.com/images/I/51iML7T0PvL._SY300_SX300_QL70_FMwebp_.jpg"/> 
		<title>The Night Circus</title>
		<description>A mystical tale of a magical competition between two illisuions, set in a dreamlike circus that apperas at night.</description>
		<author>
			<firstname>Erin</firstname> 
			<lastname>Morgenstern</lastname>
		</author>
		<ISBN>9780618743514</ISBN>
		<price>12.50</price>
		<year>2011</year>
	</book>

	<book category="fantasy">
		<bookcover url="https://m.media-amazon.com/images/I/51S-ww4ET2L._SY445_SX342_FMwebp_.jpg"/> 
		<title>Alices Adventure in Wonderland</title>
		<description>A whimsical classic about a girl who falls down a rabbit hole into a fantastical world of strange creatures and logic-defying adventures.</description>
		<author>
			<firstname>Lewis</firstname> 
			<lastname>Carroll</lastname>
		</author>
		<ISBN>9781603190241</ISBN>
		<price>10.50</price>
		<year>1865</year>
	</book>

	<book category="romance">
		<bookcover url="https://m.media-amazon.com/images/I/41YN7Ng8XYL._SY445_SX342_FMwebp_.jpg"/>
		<title>The Fault in Our Stars</title>
		<description>A heart-wrenching love story about two teens facing lifes toughest questions.</description>
		<author>
			<firstname>John</firstname> 
			<lastname>Green</lastname>
		</author>
		<price>15.10</price>
		<year>2012</year>
	</book>

	<book category="romance"> 
		<bookcover url="https://m.media-amazon.com/images/I/71xZvembMcL._SX342_.jpg"/>
		<title>The Hating Game</title>
		<description>A witty, enemies-to-lovers rom-com about office rivals.</description>
		<author>
			<firstname>Sally</firstname> 
			<lastname>Thorne</lastname>
		</author>
		<ISBN>9781713566511</ISBN>
		<price>15.55</price>
		<year>2016</year>
	</book>

	<book category="non-fiction">
		<bookcover url="https://m.media-amazon.com/images/I/71fFIwvOipL._SX342_.jpg"/>
		<title>The Power of Habit</title>
		<description>A non-fiction bestseller exploring how habits shape our lives and how we can change them.</description>
		<author>
			<firstname>Charles</firstname> 
			<lastname>Duhigg</lastname>
		</author>
		<author>Charles Duhigg</author>
		<price>14.25</price>
		<year>2012</year>
	</book>

    <book category="non-fiction"> 
		<bookcover url="https://m.media-amazon.com/images/I/51FeSmUzbRL._SY300_SX300_QL70_FMwebp_.jpg"/>
		<title>The Diary of a Young Girl</title>
		<description>A powerful true account of aa young girls's experience during World War Two offering hope and insight.</description>
		<author>
			<firstname>Anne</firstname> 
			<lastname>Frank</lastname>
		</author>
		<ISBN>9780140366286</ISBN>
		<price>25.20</price>
		<year>1947</year>
    </book>
</bookshop>
